---
# This Playbook runs all the common plays in the deployment

- name: add reverbrain gpg key
  apt_key: keyserver=keyserver.ubuntu.com id=0x5f70981d5c0e9a2f state=present

- name: add reverbain repository
  copy: src=reverbrain.list dest=/etc/apt/sources.list.d/reverbrain.list

  notify: update apt cache

- name: ensure en_RU UTF-8 locale exists
  locale_gen: name=ru_RU.UTF-8 state=present

  notify: reconfigure locales